#pragma once

enum Keys
{
    Esc = DIK_ESCAPE,
    Space = DIK_SPACE,

    Left = DIK_LEFT,
    Up = DIK_UP,
    Right = DIK_RIGHT,
    Down = DIK_DOWN,

    A = DIK_A,
    B = DIK_B,
    C = DIK_C,
    D = DIK_D,
    E = DIK_E,
    F = DIK_F,
    G = DIK_G,
    H = DIK_H,
    I = DIK_I,
    J = DIK_J,
    K = DIK_K,
    L = DIK_L,
    M = DIK_M,
    N = DIK_N,
    O = DIK_O,
    P = DIK_P,
    Q = DIK_Q,
    R = DIK_R,
    S = DIK_S,
    T = DIK_T,
    U = DIK_U,
    V = DIK_V,
    W = DIK_W,
    X = DIK_X,
    Y = DIK_Y,
    Z = DIK_Z,

    NumPad0 = DIK_NUMPAD0,
    NumPad1 = DIK_NUMPAD1,
    NumPad2 = DIK_NUMPAD2,
    NumPad3 = DIK_NUMPAD3,
    NumPad4 = DIK_NUMPAD4,
    NumPad5 = DIK_NUMPAD5,
    NumPad6 = DIK_NUMPAD6,
    NumPad7 = DIK_NUMPAD7,
    NumPad8 = DIK_NUMPAD8,
    NumPad9 = DIK_NUMPAD9,
    
    F1  = DIK_F1 ,
    F2  = DIK_F2 ,
    F3  = DIK_F3 ,
    F4  = DIK_F4 ,
    F5  = DIK_F5 ,
    F6  = DIK_F6 ,
    F7  = DIK_F7 ,
    F8  = DIK_F8 ,
    F9  = DIK_F9 ,
    F10 = DIK_F10,
    F11 = DIK_F11,
    F12 = DIK_F12,
    
    Shift = DIK_LSHIFT,
    Control = DIK_LCONTROL
};